### ISSUE TITLE
Error with threads

### ISSUE THREAD

**Issue by Pluzdev** [Mouad-scriptz/HCaptcha-Image-Scraper#1]
When I launch the tool, after putting my number of threads, the tool freeze
![image](https://user-images.githubusercontent.com/64200318/228644819-0a368593-a682-4081-bfec-8ea176e4de59.png)

**Comment by Pluzdev** [comment]
Tried with lot of proxies:
- Scraped with the tool directly
- Iproyal proxies

Same.. after entering the number of threads, nothing happen

**Comment by Mouad-scriptz** [comment]
fixed
