### ISSUE TITLE
Sorting errors

### ISSUE THREAD

**Issue by Pluzdev** [Mouad-scriptz/HCaptcha-Image-Scraper#2]
There is a lot of errors :/
Is this possible to fix this please?

![image](https://user-images.githubusercontent.com/64200318/229246972-ec60b935-98e8-454d-8834-7505ab2ed405.png)
![image](https://user-images.githubusercontent.com/64200318/229246983-2839b20e-b2aa-454f-8cd6-fa8bf67d9fc0.png)
![image](https://user-images.githubusercontent.com/64200318/229247007-b6be560d-c93b-40bd-9336-c0dac1fa06d2.png)

**Comment by Mouad-scriptz** [comment]
there is no errors it doesnt sort

**Comment by Pluzdev** [comment]
Hi i see..
Is this possible to make the tool sort them ?
